### ISSUE TITLE
add win build to feedstock

### ISSUE THREAD

**Issue by ngodber** [conda-forge/triangle-feedstock#5]
Hi guys, I'm working on modifying the recipe to include a windows build and having good success so far with everything successfully compiling. One thing I'm not familiar with exactly is what form the binary library itself should take. I see that the *nix build creates an archive and pops it into bin eg 

 trilibrary: $(BIN)triangle.o $(BIN)tricall
+	ar r $(LIB)libtri.a $(BIN)triangle.o
+	ranlib $(LIB)libtri.a

then install:

+install: trilibrary $(BIN)triangle $(BIN)showme
+	cp -f $(LIB)libtri.a $(PROTEUS_PREFIX)/lib
+	cp -f $(BIN)triangle $(BIN)showme  $(PROTEUS_PREFIX)/bin
+	cp -f triangle.h $(PROTEUS_PREFIX)/include

I'm not sure what the equivalent would be for windows. Google around quite a bit and haven't found an obvious answer. Hoping you guys can point me in the right direction!

**Comment by nehaljwani** [comment]
For Windows:
* binaries & DLLs would go under `%LIBRARY_PREFIX%\bin`
* import and static libraries would go under `%LIBRARY_PREFIX%\lib`
* headers would go under `%LIBRARY_PREFIX%\include`

You can refer to https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp to see how one can use the `lib` command to generate a static library with object files.

**Comment by nehaljwani** [comment]
It would be great if you can submit a PR, even if it is WIP

**Comment by ngodber** [comment]
Thanks for the info! My google fu was coming up short. 

re PR: Can't do it now but will in the next day or so. I considered it but because you make use of patches, which is also rather new to me, I figured that may just add noise to the question I was trying to get to. With that link I should be able to put a PR that is essentially good to go! 

One other thing: the documentation around the win conda-forge compiler was slightly unspecific. As far as I can gather it makes use of msvc so currently the plan is to have a makefile_linux.patch and a makefile_windows.patch that makes the appropriate changes. a) Sound reasonable? and b) does conda-forge win builds use msvc?

**Comment by nehaljwani** [comment]
Most of the conda-forge win builds use MSVC. For some we use the MinGW-w64 GCC compiler, but only if we have no choice and if there are no concerns about ABI compatiblity.

As for the patches - are you planning on using the Makefile for launching the build commands? Assuming the overall commands are quite a few, you may instead want to just shove them into the bld.bat (similar to build.sh for *nix) file itself.

**Comment by nehaljwani** [comment]
Resolved via https://github.com/conda-forge/triangle-feedstock/pull/6
